plugins {
    id 'java'
}

project.version = "1.0.0"
project.group = "com.yurkao"

configurations {
    testCompile.extendsFrom compileOnly
    testAnnotationProcessor.extendsFrom annotationProcessor
}

repositories {
    mavenCentral()
}

test {
    //required for Spark 3.x на Java 9+ (11, 17 и т.д.)
    jvmArgs([
        '--add-opens=java.base/java.nio=ALL-UNNAMED',
        '--add-opens=java.base/sun.nio.ch=ALL-UNNAMED',
        '--add-opens=java.base/java.lang=ALL-UNNAMED',
        '--add-opens=java.base/java.util=ALL-UNNAMED',
    ])
    useJUnitPlatform()
    testLogging.showStandardStreams = true
    testLogging.exceptionFormat = 'full'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << '-Xlint:unchecked'
    options.deprecation = true
}
ext {
    versions = [
         spark: "3.5.7",
         lombok: "1.18.42",
         junit5: "6.0.1",
         junitJupiter: "6.0.1",
         testContainers: "1.21.3",
    	 assertJ: "3.27.6",
         dnsjava: "3.6.3",
    ]
}
dependencies {

    // 1. dnsjava
    implementation("dnsjava:dnsjava:${versions.dnsjava}")
    testImplementation("dnsjava:dnsjava:${versions.dnsjava}")
    // 2. Apache Spark (spark-sql, spark-core)
    compileOnly "org.apache.spark:spark-sql_2.12:${versions.spark}"
    compileOnly "org.apache.spark:spark-core_2.12:${versions.spark}"

    testImplementation "org.apache.spark:spark-sql_2.12:${versions.spark}"
    testImplementation "org.apache.spark:spark-core_2.12:${versions.spark}"

    // 3. Lombok
    compileOnly "org.projectlombok:lombok:${versions.lombok}"
    annotationProcessor "org.projectlombok:lombok:${versions.lombok}"

    testCompileOnly "org.projectlombok:lombok:${versions.lombok}"
    testAnnotationProcessor "org.projectlombok:lombok:${versions.lombok}"

    // 4. AssertJ
    testImplementation "org.assertj:assertj-core:${versions.assertJ}"

    // 5. JUnit
    testImplementation "org.junit.jupiter:junit-jupiter-api:${versions.junit5}"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${versions.junit5}"

    testImplementation "org.junit.jupiter:junit-jupiter-api:${versions.junitJupiter}"
    testImplementation "org.junit.jupiter:junit-jupiter-params:${versions.junitJupiter}"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${versions.junitJupiter}"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // 6. TestContainers
    testImplementation "org.testcontainers:testcontainers:${versions.testContainers}"
    testImplementation "org.testcontainers:junit-jupiter:${versions.testContainers}"
}
