name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11.0.x ]
    name: Java ${{ matrix.java }} sample

    services:
      dns:
        image: internetsystemsconsortium/bind9:9.11
        options: >-
          -v ${{ github.workspace }}/dns-server/bind:/etc/bind
        ports:
          - 5353:53/udp
          - 5353:53/tcp

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew -x test build jar
