name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [created]

jobs:
  checkout:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11.0.x ]
    steps:
      - uses: actions/checkout@v2

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11.0.x ]

    services:
      dns:
        image: internetsystemsconsortium/bind9:9.11
        options: >-
           /usr/sbin/named -g  -c /etc/bind/named.conf -u root
        volumes:
          - ${{ github.workspace }}:/dns-server/bind:/etc/bind
        ports:
          - 5353:53/udp
          - 5353:53/tcp

    name: Java ${{ matrix.java }} sample

    steps:

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew -x test build jar
